### ISSUE TITLE
Extending the catalog of recognized built-in elements

### ISSUE THREAD

**Issue by bnjm** [vuejs/jsx-next#119]
Since Vue 3 allows for custom renderers as an alternative to @vue/runtime-dom, A custom runtime might have it's own collection of 'native' elements. See [Vugel](https://github.com/Planning-nl/vugel) for a good example. It supports built-in tags like `<shader>` and `<container>`. 

At the moment `@vue/babel-plugin-jsx` will flag unknown native elements as a `callExpression` (https://github.com/vuejs/jsx-next/blob/dev/packages/babel-plugin-jsx/src/utils.ts#L111) if they are not matched in the catalog of known svg or html tags. How can we allow new native elements to be compatible JSX in Vue?

**Comment by Amour1688** [comment]
Do you mean `isCustomElement` ?

**Comment by bnjm** [comment]
@Amour1688 yes that works, thanks! I saw it but thought it was a web components thing
