### ISSUE TITLE
能否使用slots和KeepAlive缓存

### ISSUE THREAD

**Issue by Buzz888** [vuejs/jsx-next#144]
vue template
``` vue
<router-view v-slot="{ Component }">
  <keep-alive>
    <component :is="Component" />
  </keep-alive>
</router-view>
```
How to use it in JSX？

**Comment by Zcating** [comment]
use <KeepAlive> & <Component> 

`import {KeepAlive, Component} from 'vue'`

**Comment by Zcating** [comment]
slots usage.
```
<SomeCompo v-slots={{default: () => <div>hello</div>, header: () => <div>this is header</div>}} />


// in some-compo.tsx
export const SomeCompo = (_, ctx) => {
  return () => {

    <div>
      {renderSlot(ctx.slots, 'header')}
      {renderSlot(ctx.slots, 'default')}
    </div>
  }
}
```

this will render like this

<div>
  <div>this is header</div>
  <div>hello</div>
</div>

**Comment by Swedish-li** [comment]
> use `<KeepAlive> & <Component> `
> 
> `import {KeepAlive, Component} from 'vue'`

in the vue's source I can only find  `Component` is a component type.

when I really use `Component`  I can see  error messge :`'Component' only refers to a type, but is being used as a value here.` in vscode.

![image](https://user-images.githubusercontent.com/17829108/97096749-7ef2eb80-16ab-11eb-98a3-5087cdbea965.png)


in vue `runtime-core.d.ts`:

```typescript
/**
 * A type used in public APIs where a component type is expected.
 * The constructor type is an artificial type returned by defineComponent().
 */
export declare type Component<Props = any, RawBindings = any, D = any, C extends ComputedOptions = ComputedOptions, M extends MethodOptions = MethodOptions> = ConcreteComponent<Props, RawBindings, D, C, M> | ComponentPublicInstanceConstructor<Props>;

```
What I missed ?

**Comment by Zcating** [comment]
@Swedish-li  OK. This is my fault. `<component>` will render as `resolveDynamicComponent` . here is e.g:
```
<KeepAlive>
  {resolveDynamicComponent(/* The component you want to pass or the component string you already define */)}
</KeepAlive>
```

**Comment by Swedish-li** [comment]
@Zcating  Thanks !

**Comment by lilililee** [comment]
How to use my custom global component？must use import？

**Comment by Zcating** [comment]
Import is the best way using in tsx. You don't need to define the local component name in `component` prop of Vue instance.
```
import { SomeCompo } from 'some-compo-lib';
```
