### ISSUE TITLE
Should support passing object slots via JSX children

### ISSUE THREAD

**Issue by yyx990803** [vuejs/jsx-next#147]
I may have missed the reasoning but I just noticed the usage of `v-slots` which is quite odd.

A more straightforward syntax should be:

```jsx
const slots = {
  default: () => <div>default</div>,
  foo: () => <div>bar</div>
}
<Comp>{slots}</Comp>
```

Or inline:

```jsx
<Comp>{{
  default: () => <div>default</div>,
  foo: () => <div>bar</div>
}}</Comp>
```

**Comment by Zcating** [comment]
Finally, You found it.

The usage of `v-slots` is quite react-like, may be provide more radical syntax sugar.

```
<Compo>
  <VSlot name="default">
      <div>default</div>
  </VSlot>
  <VSlot name="foo">
      <div>bar</div>
  </VSlot>
</Compo>
```

**Comment by yyx990803** [comment]
Discussion notes from Discord:

Previous decision to use `v-slots` due to difficulty in determining the case where a dynamic expression is embedded:

```jsx
const s = {
  foo: () => <div>foo</div>,
  bar: () => <div>bar</div>
}
<Comp>{s}</Comp>
```

Current output is

```js
createVNode(resolveComponent("Comp"), null, {
  default: () => [s],
  _: 1
})
```

The solution is to add a runtime check:

```js
const isSlot = s => isFunction(s) || (isObject(s) && !isVNode(s))

createVNode(resolveComponent("Comp"), null, isSlot(s) ? s : {
  default: () => [s],
  _: 1
})
```

The runtime check should only be needed in the case where:

- The JSX component has a single children expression
- The children expression is not a literal value (identifier, function call, other non-literal expressions)

### Expected Cases

May not be complete.

- JSX children: compile to default slot

    ```jsx
    <Comp><div>hi</div></Comp>

    createVNode(resolveComponent("Comp"), null, {
      default: () => [createVNode("div", null, [createTextVNode("hi")])],
      _: 1
    })
    ```

- Multiple expressions: compile to default slot

    ```jsx
    <Comp>{foo} {bar}</Comp>

    createVNode(resolveComponent("Comp"), null, {
      default: () => [foo, createTextVNode(" "), bar],
      _: 1
    })
    ```

- Single expression, non-literal value: runtime check

    Note: may need to cache the expression in a variable to avoid multiple evaluations

    ```jsx
    <Comp>{foo()}</Comp>

    let _slot_1
    createVNode(resolveComponent("Comp"), null, isSlot(_slot_1 = foo()) ? _slot_1 : {
      default: () => [_slot_1],
      _: 1
    })
    ```

- Single expression, object literal: pass as object slots

    ```jsx
    <Comp>{{
      default: () => <div>default</div>,
      foo: () => <div>foo</div>
    }}</Comp>

    createVNode(resolveComponent("Comp"), null, {
      default: () => createVNode("div", null, [createTextVNode("default")]),
      foo: () => createVNode("div", null, [createTextVNode("foo")]),
      _: 1
    })
    ```

- Single expression, function expression: pass as default slot (no wrapping, no flag)

    ```jsx
    <Comp>{() => "foo"}</Comp>

    createVNode(resolveComponent("Comp"), null, {
      default: () => "foo"
      // probably should have no flag here
    })
    ```

- Single expression, other literals: pass as default slot

    ```jsx
    <Comp>{123}</Comp>

    createVNode(resolveComponent("Comp"), null, {
      default: () => [normalizeVNode(123)],
      _: 1
    })
    ```

**Comment by 0x30** [comment]
Is there any news about this new feature?  👀👀👀👀

**Comment by Amour1688** [comment]
> Is there any news about this new feature? 👀👀👀👀

WIP

**Comment by nickmessing** [comment]
Would be nice to add [children typing](https://www.typescriptlang.org/docs/handbook/jsx.html#children-type-checking) support if this is implemented.
