### ISSUE TITLE
Bind multiple V- model.sync

### ISSUE THREAD

**Issue by Buzz888** [vuejs/jsx-next#150]
template
```vue
<div  
    v-model:expandedKeys="expandedKeys"
    v-model:selectedKeys="selectedKeys"
    v-model:checkedKeys="checkedKeys">
</div>
```
How to use it in JSX？
```jsx
<div 
v-model={[expandedKeys,'expandedKeys']}>
v-model={[selectedKeys,'selectedKeys']}>
</div>
JSX elements cannot have more than one attribute with the same name
```

**Comment by Zcating** [comment]
Have you seen the README.md?
You need to pass the ARRAY but a bracket containered something parser unkown.

```
<div 
v-model={[expandedKeys, 'expandedKeys']}>
v-model={[selectedKeys, 'selectedKeys']}>
</div>
```

**Comment by Buzz888** [comment]
> 您看过README.md吗？
> 您需要传递ARRAY，但要使用一个装有未知解析器的括号。
> 
> ```
> <div 
> v-model={[expandedKeys, 'expandedKeys']}>
> v-model={[selectedKeys, 'selectedKeys']}>
> </div>
> ```
It's wrong to write a report like this
I've seen it, but the V-model can't bind multiple modifiers
JSX elements cannot have more than one attribute with the same name

**Comment by Amour1688** [comment]
See https://github.com/vuejs/jsx-next/pull/140

**Comment by Buzz888** [comment]
@Amour1688 Thanks !
