### ISSUE TITLE
How to use v-model in component？

### ISSUE THREAD

**Issue by lilililee** [vuejs/jsx-next#151]
// index.tsx
![image](https://user-images.githubusercontent.com/24242242/97299776-76a7d580-1890-11eb-8d91-987a2c589dc0.png)

// Modal.tsx
![image](https://user-images.githubusercontent.com/24242242/97299819-858e8800-1890-11eb-96f0-969781bf476f.png)

I refer `<A v-model={[val, 'argument', ['modifier']]} />`, but got typescript error.

Version:
vue: `3.0.2`
@vue/babel-plugin-jsx: `1.0.0-rc.3`
typescript: `3.9.7`

**Comment by Zcating** [comment]
Not your fault, the props definition has bug. You need to do this.

```
props: {
  modelValue: {
    type: Boolean,
    required: true,
  } as Prop<boolean>
}

```

**Comment by Zcating** [comment]
Have you checked your Vue version?

**Comment by Amour1688** [comment]
missing required `modelValue`

**Comment by Zcating** [comment]
Maybe remove the `required` key in props or add `modelValue={state.visible}` in the tag attribute.

**Comment by lilililee** [comment]
@Amour1688 Typescript error has gone after missing required `modelValue` and `v-model` already work, but I think `modelValue` set `required: true` is nothing wrong. Is it a bug?

**Comment by Amour1688** [comment]
> @Amour1688 Typescript error has gone after missing required `modelValue` and `v-model` already work, but I think `modelValue` set `required: true` is nothing wrong. Is it a bug?

![image](https://user-images.githubusercontent.com/31695475/97383510-c4602480-1908-11eb-8941-d459c7ac56c5.png)

**Comment by TheDutchCoder** [comment]
This issue shouldn't be closed, requiring a v-model is very normal and jsx should know how to map `v-model` to `modelValue`.

**Comment by chaozwn** [comment]
i think this problem should be solved.i think it may be a typescript problem. `v-model:modelValue.trim` also has question.
