### ISSUE TITLE
function children should not be parsed

### ISSUE THREAD

**Issue by Jokcy** [vuejs/jsx-next#16]
```
<Comp>
{() => <span></span>}
</Comp>
```

By default slot will be parsed to function to be performent, but if we write it to a function, it should stay that instead of wrap it to another function.

I think `() => <span></span>` is just what we called `scopedSlot` in vue.

**Comment by Jokcy** [comment]
I can PR if you guys are busy

**Comment by Amour1688** [comment]
> I can PR if you guys are busy

from `dev` branch

**Comment by Amour1688** [comment]
#26

**Comment by Amour1688** [comment]
#147
