### ISSUE TITLE
slot中支持template标签么？

### ISSUE THREAD

**Issue by superwy** [vuejs/jsx-next#165]
在slot中使用template标签不显示

`            const slots = {
                default: () => {
                    <template>
                        <NavMenuItem />
                        <NavMenuItem />
                    </template>
                }
            }
`

**Comment by Zcating** [comment]
use `<></>`

**Comment by Zcating** [comment]
使用模板的时候会把 `<template>` 渲染成 `<Fragment>`。在 jsx 中，你需要通过 `import {Fragment} from 'vue'`这种形式引入，并将其当作标签使用即可。
`const slots = { default: () => { <Fragment> <NavMenuItem /> <NavMenuItem /> </Fragment> } }`

**Comment by wpbjiuy** [comment]
v-slots 只能在根目录下才起做用，而且<></>这怎么放呢？ < v-slots={slots}></>这样吗？
