### ISSUE TITLE
Does not support multiple v-models

### ISSUE THREAD

**Issue by Linkontoask** [vuejs/jsx-next#166]
https://v3.vuejs.org/guide/migration/v-model.html#v-model-arguments

```
<A
  v-model={[value, 'value']} 
  v-model={[visible, 'visible']}  />
```

`JSX elements cannot have multiple attributes with the same name`

**Comment by sqal** [comment]
Yes

**Comment by sqal** [comment]
https://vue-next-jsx-explorer.netlify.app/#const%20App%20%3D%20()%20%3D%3E%20(%0D%0A%20%20%3CA%0D%0A%20%20%20%20v-models%3D%7B%5B%0D%0A%20%20%20%20%20%20%5Bvalue%2C%20'value'%5D%2C%0D%0A%20%20%20%20%20%20%5Bvisible%2C%20'visible'%5D%2C%0D%0A%20%20%20%20%5D%7D%0D%0A%20%20%2F%3E%0D%0A)

**Comment by niuxinyu** [comment]
> https://vue-next-jsx-explorer.netlify.app/#const%20App%20%3D%20()%20%3D%3E%20(%0D%0A%20%20%3CA%0D%0A%20%20%20%20v-models%3D%7B%5B%0D%0A%20%20%20%20%20%20%5Bvalue%2C%20'value'%5D%2C%0D%0A%20%20%20%20%20%20%5Bvisible%2C%20'visible'%5D%2C%0D%0A%20%20%20%20%5D%7D%0D%0A%20%20%2F%3E%0D%0A)


How should I use it? It caused an error when using it.
![image](https://user-images.githubusercontent.com/45762373/98615558-e197e880-2335-11eb-8319-9de89c9d0642.png)
![image](https://user-images.githubusercontent.com/45762373/98615569-ea88ba00-2335-11eb-8d72-98ee9dc22ab0.png)

**Comment by sqal** [comment]
@niuxinyu oh, that's because this feature has not been published yet. You probably have to wait for the next release.

**Comment by nour-dev** [comment]
@sqal not released in vue 3? or in jsx-next ?

**Comment by sqal** [comment]
@nour-dev @vue/babel-plugin-jsx

**Comment by Amour1688** [comment]
it will release this week

**Comment by wpbjiuy** [comment]
怎么支持多个v-model啊
![image](https://user-images.githubusercontent.com/18400376/99748777-1ebf6000-2b18-11eb-88f8-672cdb7abc4e.png)
