### ISSUE TITLE
[docs] 文档可以补充具体一点

### ISSUE THREAD

**Issue by ajuner** [vuejs/jsx-next#176]
- 建议使用vModel
- 自定义组件建议使用vCustom
- directives: { custom: customDirective }中customDirective 该怎么用
- slots子组件该怎么写
- emit怎么写

**Comment by TimRChen** [comment]
在jsx中使用 slots 时， v-slots={this.$slots} 即可

**Comment by ajuner** [comment]
只是建议把文档补充下，而且是想写在setup里的
