### ISSUE TITLE
Feature Request: $attrs type enhancement

### ISSUE THREAD

**Issue by Zcating** [vuejs/jsx-next#181]
```
const Child = defineComponent({
  props: {
    label: String
  },
  setup(_, ctx) {
    return () => [
      <div>{_.label}</div>,
      <input {...ctx.attrs}/>
    ];
  }
});

const Parent = defineComponent(() => {
  return () => <Child label="test" placeholder="please input"/>;
});
```

This code will show a error as following.

> Type '{ label: string; placeholder: string; }' is not assignable to type 'IntrinsicAttributes & Partial<{}> & Pick<Readonly<{} & { label?: string | undefined; }> & VNodeProps & AllowedComponentProps & ComponentCustomProps, "label" | ... 9 more ... | "class">'.
  Property 'placeholder' does not exist on type 'IntrinsicAttributes & Partial<{}> & Pick<Readonly<{} & { label?: string | undefined; }> & VNodeProps & AllowedComponentProps & ComponentCustomProps, "label" | ... 9 more ... | "class">'

**Comment by Amour1688** [comment]
You should declare type in `Child` component.

**Comment by Amour1688** [comment]
```tsx
import { defineComponent, ExtractPropTypes, HTMLAttributes } from 'vue';

const childProps = {
  label: String
}

export type ChildProps = ExtractPropTypes<typeof childProps> & HTMLAttributes

const Child = defineComponent<ChildProps>({
  setup(_, ctx) {
    return () => [
      <div>{_.label}</div>,
      <input {...ctx.attrs}/>
    ];
  }
});

Child.props = childProps

const Parent = defineComponent(() => {
  return () => <Child label="test" placeholder="please input"/>;
});
```

**Comment by Zcating** [comment]
Accepted.
