### ISSUE TITLE
在 lang="ts"时，使用jsx会报错 Cannot find name 'div'

### ISSUE THREAD

**Issue by LgnMs** [vuejs/jsx-next#188]
```
<script lang="ts">
...
render() {
    return <div></div> // Cannot find name 'div'.Vetur(2304)
}
</script>
```
在js状态下正常

**Comment by Zcating** [comment]
`lang="tsx"`

**Comment by fallenleavesguy** [comment]
lang="tsx" <div>hello</div>变成了hello</div>
  52 |         //   )
  53 |         // }
> 54 |         const node = (hello < /div>));
     |                                ^
  55 |         const __returned__ = { node };
  56 |         Object.defineProperty(__returned__, '__isScriptSetup', { enumerable: false, value: true });
  57 |         return __returned__;
