### ISSUE TITLE
How to use v-if and v-else instructions

### ISSUE THREAD

**Issue by Linkontoask** [vuejs/jsx-next#193]
version "1.0.0-rc.3"

```
<div v-if={true}>jsx</div>
<div v-else>vue</div>
```

```
runtime-core.esm-bundler.js?5c40:38 [Vue warn]: Failed to resolve directive: else
Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/vue-next
.......
```

If I use ternary expressions to achieve, the transition system cannot be triggered

[demo](https://vue-next-jsx-explorer.netlify.app/#const%20App%20%3D%20()%20%3D%3E%20(%0D%0A%20%20%3Cdiv%3E%0D%0A%20%20%20%20%3CA%20v-if%3D%7Btrue%7D%20%2F%3E%0D%0A%20%20%20%20%3CB%20v-else%20%2F%3E%0D%0A%20%20%3C%2Fdiv%3E%0D%0A)%0D%0A%0D%0Aconst%20App1%20%3D%20()%20%3D%3E%20(%0D%0A%20%20%3C%3E%0D%0A%20%20%20%7Btrue%20%3F%20%3CA%20%2F%3E%20%3A%20%3CB%20%2F%3E%7D%0D%0A%20%20%3C%2F%3E%0D%0A)%0D%0A)

I am guessing if there is an unknown error in the `resolveDirective` function

**Comment by Amour1688** [comment]
```js
condition ? <div /> : <span />
```

**Comment by Linkontoask** [comment]
Can this use trigger transition animation?
