### ISSUE TITLE
compile errors about v-model and emits events

### ISSUE THREAD

**Issue by yuelinghunyu** [vuejs/jsx-next#200]
` <PullRefresh 
      v-model={false} 
      on-refresh={refreshEvent}
    >
    </PullRefresh>
`

TypeError: ***/App.tsx: Property left of AssignmentExpression expected node to be of a type ["LVal"] but instead got "BooleanLiteral"

**Comment by Amour1688** [comment]
1. `v-model`'s value should be a identifier.
2. onRefresh
