### ISSUE TITLE
return to jsx in setup, an error will be reported

### ISSUE THREAD

**Issue by Jonny-china** [vuejs/jsx-next#220]
vue: 3.0.4
@vue/compiler-sfc: 3.0.4
@vue/babel-plugin-jsx: 1.0.0-rc.5

I set `lang="tsx"` in the .vue file.

```vue
<script lang="tsx">
import { defineComponent } from 'vue'
export default defineComponent({
  setup() {
    return () => <div></div>
  }
})
</script>
```

Error message:
```
Module parse failed: Unexpected token (74:36)
File was processed with these loaders:
 * ./node_modules/cache-loader/dist/cjs.js
 * ./node_modules/ts-loader/index.js
 * ./node_modules/cache-loader/dist/cjs.js
 * ./node_modules/vue-loader-v16/dist/index.js
You may need an additional loader to handle the result of these loaders.
| export default defineComponent({
|     setup: function () {
>         return function () { return <div></div>; };
|     }
| });
```

**Comment by Ttou** [comment]
用了 jsx 就别用 sfc 了，它也不支持 scoped 样式

**Comment by sodatea** [comment]
![image](https://user-images.githubusercontent.com/3277634/102158125-b4ea6a00-3ebb-11eb-80a0-08850381eb38.png)

Babel is required for JSX/TSX.

**Comment by Jonny-china** [comment]
> ![image](https://user-images.githubusercontent.com/3277634/102158125-b4ea6a00-3ebb-11eb-80a0-08850381eb38.png)
> 
> Babel is required for JSX/TSX.

Thanks, this problem has been resolved, and `@vue/cli-plugin-babel` dependency is not installed
