### ISSUE TITLE
Does it support the v-for?

### ISSUE THREAD

**Issue by Vgbire** [vuejs/jsx-next#229]
Since it supports some instructions, such as v-show and V-model, can JSX loop only use map? Because I made a mistake trying to use V-for in JSX

**Comment by Zcating** [comment]
Yes. You should impl your own v-for.

**Comment by Vgbire** [comment]
![image](https://user-images.githubusercontent.com/32129111/102320234-fb70bf00-3fb6-11eb-8d1c-a313b510bb7c.png)
Do you mean let me customize an instruction to implement the function of V-for? I mean can we use Vue defined V-for directly?

**Comment by Vgbire** [comment]
> Yes. You should impl your own v-for.
![image](https://user-images.githubusercontent.com/32129111/102320464-48ed2c00-3fb7-11eb-9168-4a6d7e630a12.png)
Do you mean let me customize an instruction to implement the function of V-for? I mean can we use Vue defined V-for directly?

**Comment by Zcating** [comment]
No, I mean you should create a pull request.
