### ISSUE TITLE
How can I use JSX with script setup ?

### ISSUE THREAD

**Issue by oomusou** [vuejs/jsx-next#253]
`
<script setup>
export let render = () => <p>Hello Vue 3</p>
</script>
`

I got following error

`
Syntax Error: TypeError: Cannot read property 'content' of null
`

**Comment by Zcating** [comment]
```
<script lang="jsx">

</script>
```

**Comment by moixxsyc** [comment]
<script setup>
const inst = getCurrentInstance()
inst.render = ()=> Hello Vue 3
</script>

**Comment by moixxsyc** [comment]
`
<script setup>
 const inst = getCurrentInstance()
 inst.render = ()=> Hello Vue 3 
</script>
`

**Comment by moixxsyc** [comment]
`<script setup> 

const inst = getCurrentInstance()

 inst.render = ()=> Hello Vue 3

 </script>

`

**Comment by kunbo-Jiang** [comment]
> `<script setup>
> 
> const inst = getCurrentInstance()
> 
> inst.render = ()=> Hello Vue 3
> 
> </script>
> `

Don't have any effect

**Comment by kunbo-Jiang** [comment]
render function is not supported in this scenario. Please use one normal <script> with setup option instead.
document display

**Comment by Mrcxt** [comment]
I have the same problem
