### ISSUE TITLE
WithModifiers 对按键修饰符不起作用

### ISSUE THREAD

**Issue by ZhengXiaowei** [vuejs/jsx-next#269]
```
<input onKeyup={withModifiers(() => console.log(1), ["enter"])} />
```
实际效果，键盘的每个按键结束都会触发`console.log(1)`

**Comment by Zcating** [comment]
请提供一个最小demo...

**Comment by ZhengXiaowei** [comment]
https://codesandbox.io/s/broken-sound-i2e8m?file=/src/App.jsx

**Comment by Zcating** [comment]
源码的 Modifier 并没有提供 'enter' 这个 key。
``` typescript
const modifierGuards: Record<
  string,
  (e: Event, modifiers: string[]) => void | boolean
> = {
  stop: e => e.stopPropagation(),
  prevent: e => e.preventDefault(),
  self: e => e.target !== e.currentTarget,
  ctrl: e => !(e as KeyedEvent).ctrlKey,
  shift: e => !(e as KeyedEvent).shiftKey,
  alt: e => !(e as KeyedEvent).altKey,
  meta: e => !(e as KeyedEvent).metaKey,
  left: e => 'button' in e && (e as MouseEvent).button !== 0,
  middle: e => 'button' in e && (e as MouseEvent).button !== 1,
  right: e => 'button' in e && (e as MouseEvent).button !== 2,
  exact: (e, modifiers) =>
    systemModifiers.some(m => (e as any)[`${m}Key`] && !modifiers.includes(m))
}
```

**Comment by ZhengXiaowei** [comment]
> 源码的 Modifier 并没有提供 'enter' 这个 key。
> ``` typescript
> const modifierGuards: Record<
>   string,
>   (e: Event, modifiers: string[]) => void | boolean
> > = {
>   stop: e => e.stopPropagation(),
>   prevent: e => e.preventDefault(),
>   self: e => e.target !== e.currentTarget,
>   ctrl: e => !(e as KeyedEvent).ctrlKey,
>   shift: e => !(e as KeyedEvent).shiftKey,
>   alt: e => !(e as KeyedEvent).altKey,
>   meta: e => !(e as KeyedEvent).metaKey,
>   left: e => 'button' in e && (e as MouseEvent).button !== 0,
>   middle: e => 'button' in e && (e as MouseEvent).button !== 1,
>   right: e => 'button' in e && (e as MouseEvent).button !== 2,
>   exact: (e, modifiers) =>
>     systemModifiers.some(m => (e as any)[`${m}Key`] && !modifiers.includes(m))
> }
> ```

有打算加入吗

**Comment by Zcating** [comment]
可以去 vue-next 仓库里面提这个 issue。

**Comment by ZhengXiaowei** [comment]
OK 明天我看看withkeys

**Comment by ZhengXiaowei** [comment]
ok 奏效 谢谢

**Comment by wenfangdu** [comment]
@Zcating @ZhengXiaowei 
 
> [If you are using JSX, you should just handle key events yourself. Exposing `withKeys` locks us into how it works and prevents potential future changes in internal implementations.](https://github.com/vuejs/vue-next/issues/3827#issuecomment-847850757).
