### ISSUE TITLE
vue sfc with jsx and style scoped cannot show correctly

### ISSUE THREAD

**Issue by baojie223** [vuejs/jsx-next#275]
example: [codesandbox](https://codesandbox.io/s/nameless-shadow-5gtff?file=/src/App.vue)

the scoped id will show as data-v-**-s, but the style is correct, so the style wont work

![image](https://user-images.githubusercontent.com/27616710/104705992-86c7a680-5755-11eb-9b85-06d7a57b45a3.png)
![image](https://user-images.githubusercontent.com/27616710/104706043-9646ef80-5755-11eb-818b-0a0d81e052ef.png)

**Comment by baojie223** [comment]
@Amour1688 please check this

**Comment by Amour1688** [comment]
```js
import { withScopeId } from 'vue'; 
export default {
  name: "App",
 render(ctx) {
    return withScopeId(ctx._.type.__scopeId)(() => (
      <div class="lg">app</div>
    ))()
  }
};```
