### ISSUE TITLE
label:bug  不支持自定义指令的动态参数 dynamic directive arguments are NOT supported in custom directives 😭

### ISSUE THREAD

**Issue by hellofreckles** [vuejs/jsx-next#279]
same as title

**Comment by TNTrocket** [comment]
how to use  dynamic directive arguments in custom directives

**Comment by Amour1688** [comment]
> how to use dynamic directive arguments in custom directives

https://vue-next-jsx-explorer.netlify.app/#%3CA%20v-xx%3D%7B%5Bd%2C%20x%2C%20%5B'a'%2C%20'b'%5D%5D%7D%20%2F%3E
