### ISSUE TITLE
Vue3.x tsx 使用Element-plus ElSubmenu组件插值无效

### ISSUE THREAD

**Issue by gouqingping** [vuejs/jsx-next#284]
`
 const slots = {
            title: () => {
                return <>
                    <i class={`${meta && meta.icon} iconfont`}></i>
                    <span>{meta && meta.title}</span>
                </>
            }
        }；
<ElSubmenu index={path} key={path} class={meta.class} v-slots={[slots]}>
                                    {children.map((child: any) => {
                                        return <SidebarItem menus={child} parentPath={path}></SidebarItem>
                                    })}
                                </ElSubmenu>
`

**Comment by Amour1688** [comment]
try
`v-slots={slots}`

**Comment by gouqingping** [comment]
> try
> `v-slots={slots}`

.tsx mode development is not good.
