### ISSUE TITLE
“tsx Transition KeepAlive” exception occurred

### ISSUE THREAD

**Issue by 0x30** [vuejs/jsx-next#286]
https://github.com/vuejs/vue-next/issues/3097

**Comment by 0x30** [comment]
你好，现在这个问题，有任何进度吗？

### Version
3.0.5

### Reproduction link
[https://github.com/0x30/vue-transition-keepalive-error](https://github.com/0x30/vue-transition-keepalive-error)

### Steps to reproduce
1. Clone the code to local
2. npm install & run

An error occurred

### What is expected?
Same as template syntax, normal operation

### What is actually happening?

I added these codes and the following problems occurred

https://github.com/0x30/vue-transition-keepalive-error/commit/0396d47ba150956f9f2f5a4217821440b2d5f492

![image](https://user-images.githubusercontent.com/6121524/105797934-f8141e80-5fcb-11eb-8ff4-a28060a18cb9.png)

**Comment by Amour1688** [comment]
https://github.com/vuejs/jsx-next/commit/f1c9629b88341efc01cf7ae049047fa5110043b4
