### ISSUE TITLE
[Question] Non-prop attributes in TSX component

### ISSUE THREAD

**Issue by pynnl** [vuejs/jsx-next#313]
### 🧐 Problem Description
Hi. How to skip type check on non-prop attributes beside `class` and `style` when using TSX (I'd like to avoid using prop)?
Since attribute inheritance is a legit feature, I guess the component should allow any additional props?

### 💻 Sample code
```tsx
export const NavBar = defineComponent(() => {
  return () => (
    <div>
      <NavBarButton title="Writing Editor" route="writing" />
    </div>
  );
});

export const NavBarButton = defineComponent({
  props: {
    route: {
      type: String,
      required: true,
    },
  },
  setup({route}) {
    return () => <i onClick={() => (appData.activeRoute = route)} />;
  },
});
```
![image](https://user-images.githubusercontent.com/31667324/107417544-b9aa5380-6ae3-11eb-84c5-6e0054b39188.png)

**Comment by Jokcy** [comment]
It's TS approach, in your component you only define route as props. If you want to tell ts that your component accept dom attrs, you can simplely import `import { HTMLAttributes } from vue` and use it to define you component.

NOTE: different dom element type has different export name in vue

**Comment by pynnl** [comment]
@Jokcy Thanks for the solution. I'm still wondering why it doesn't allow us to pass any props to the component, because [attribute inhertiance](https://v3.vuejs.org/guide/component-attrs.html#attribute-inheritance) is a valid feature.

**Comment by LinusBorg** [comment]
If TSX allows you to pass any props, you won't receive warnings when you pass a wrong prop i.e. passing `rote` instead of `route` would be fine, even though it's a typo.

That kind of defeats the purpose of using TS(X)
