### ISSUE TITLE
[Proposal] namespaced JSX elements and attributes will be available in ts 4.2

### ISSUE THREAD

**Issue by JounQin** [vuejs/jsx-next#325]
### 🚑 Other information

```tsx
const foo = <n:a n:v />;
```

Although it means different with Vue modifier by default, but can we write a ts plugin to support it as Vue modifier just like template?

https://github.com/microsoft/TypeScript/pull/37421

**Comment by pynnl** [comment]
I like this, because I have to write `v-model={[val, 'propName']}` a lot. I'd be great if I can just do `v-model:propName={val}`.
