### ISSUE TITLE
How to define default slot?

### ISSUE THREAD

**Issue by linkscope** [vuejs/jsx-next#336]
Hello, Now I want to define a slot and default slot, but I didn't find any good way. please help me to resolve this. 

### 💻 Sample code
```ts
renderSlot(slots, 'default')

// this is what I want to define the default slot
<Button type="primary" htmlType="submit">登录</Button>
```

**Comment by XeryYue** [comment]
at first .you can try this way to define default slot

```javascript
//define

const Button = defineComponent({
  props: {
    round: Boolean,
    color: String,
    size: {
      type: String,
      default: "normal",
      validator: enums(["mini", "small", "normal", "large"])
    }
  },
  emits: ["click"],
  setup(props, { attrs, slots, emit }) {
    const handleClick = event => emit("click", event);
    return () => (
      <>
        <div onClick={handleClick} {...attrs}>
          {slots && slots.default()}
        </div>
      </>
    );
  }
});

//You can use this in other files

<Button >I am button</Button>

```


// define more slots

```javascript

const MoreSlot = defineComponent({
  setup(props, { attrs, slots, emit }) {
    return () => (
      <>
        <div >
         <div> {slots && slots.default()}</div>
         <div>{slots && `youer slots name`() }</div> 
        </div>
      </>
    );
  }
});

```

**Comment by linkscope** [comment]
> at first .you can try this way to define default slot
> 
> ```js
> //define
> 
> const Button = defineComponent({
>   props: {
>     round: Boolean,
>     color: String,
>     size: {
>       type: String,
>       default: "normal",
>       validator: enums(["mini", "small", "normal", "large"])
>     }
>   },
>   emits: ["click"],
>   setup(props, { attrs, slots, emit }) {
>     const handleClick = event => emit("click", event);
>     return () => (
>       <>
>         <div onClick={handleClick} {...attrs}>
>           {slots && slots.default()}
>         </div>
>       </>
>     );
>   }
> });
> 
> //You can use this in other files
> 
> <Button >I am button</Button>
> ```
> 
> // define more slots
> 
> ```js
> const MoreSlot = defineComponent({
>   setup(props, { attrs, slots, emit }) {
>     return () => (
>       <>
>         <div >
>          <div> {slots && slots.default()}</div>
>          <div>{slots && `youer slots name`() }</div> 
>         </div>
>       </>
>     );
>   }
> });
> ```
> 
> @linkscope

sorry, I mean that I don't konw how to define fallback content
We might want the text “Submit” to be rendered inside the <button> most of the time.
```ts
<button type="submit">
  <slot>Submit</slot>
</button>
```
how to do this?

**Comment by XeryYue** [comment]
Sorry, I don't know you mean, But may you can define a default context in your components  and  use props to control the default
context show or hide. @linkscope

**Comment by linkscope** [comment]
> Sorry, I don't know you mean, But you can define a default context in your components and use props to control the default
> context show or hide. @linkscope

后备内容，Vue官方称其为fallback content，即如果不使用该插槽会默认显示的内容，我现在不清楚如何设置

**Comment by XeryYue** [comment]
> 
> 后备内容，Vue官方称其为fallback content，即如果不使用该插槽会默认显示的内容，我现在不清楚如何设置
> 
> ```ts
> <slot>如果不使用该插槽，默认展示这里的数据</slot>
> ```

好吧，我觉得你想表达的是不是这样？

```js
import { defineComponent } from "vue";

const Component = defineComponent({
  setup(props, { slots }) {
    const safeSlots = !!slots?.default;
    const defaultMessage = () => <span>默认信息</span>;

    return () => <div>{safeSlots ? slots.default() : "你想要的默认信息或者你写个渲染函数放这里"}</div>;
  }
});

```

**Comment by linkscope** [comment]
> > 后备内容，Vue官方称其为fallback content，即如果不使用该插槽会默认显示的内容，我现在不清楚如何设置
> > ```ts
> > <slot>如果不使用该插槽，默认展示这里的数据</slot>
> > ```
> 
> 好吧，我觉得你想表达的是不是这样？
> 
> ```js
> import { defineComponent } from "vue";
> 
> const Component = defineComponent({
>   setup(props, { slots }) {
>     const safeSlots = !!slots?.default;
>     const defaultMessage = () => <span>默认信息</span>;
> 
>     return () => <div>{safeSlots ? slots.default() : "你想要的默认信息或者你写个渲染函数放这里"}</div>;
>   }
> });
> ```
> 
> @linkscope

OK, 感谢回答，但是否有更优雅的解法？因为之前一直在使用vue提供的renderSlot函数，查看源码后也发现该函数的最后一个参数是fallback content，但查看官网后没发现该函数的具体使用方法

**Comment by linkscope** [comment]
OK, 我已经解决了该问题，最后使用h函数成功渲染出了后备内容，感谢您的回答
```ts
            {renderSlot(slots, 'default', {}, () => [
              h(
                Button,
                {
                  loading: store.state.isLoading,
                  type: 'primary',
                  htmlType: 'submit',
                  shape: 'round',
                  size: 'large'
                },
                '完成'
              )
            ])}
```

**Comment by Iongtao** [comment]
> OK, 我已经解决了该问题，最后使用h函数成功渲染出了后备内容，感谢您的回答
> 
> ```ts
>             {renderSlot(slots, 'default', {}, () => [
>               h(
>                 Button,
>                 {
>                   loading: store.state.isLoading,
>                   type: 'primary',
>                   htmlType: 'submit',
>                   shape: 'round',
>                   size: 'large'
>                 },
>                 '完成'
>               )
>             ])}
> ```

也可以直接使用jsx的写法：
> ```ts
>             {renderSlot(slots, 'default', {}, () => [<button type='primary' html-type='submit' shape='round'>完成</button>])}
> ```
