### ISSUE TITLE
[Question] How to handle events containing `:`

### ISSUE THREAD

**Issue by PeterParker** [vuejs/jsx-next#344]
### 🧐 Problem Description

Consider a component `current-component`, which utilizes a child component `child-component` in standard SFC syntax as follows:

```vue
<template>
  <child-component
    :item="item"
    @update:item="onItemUpdated"
  ></child-component>
</template>

<script>
import ChildComponent from "./ChildComponent.vue";

export default defineComponent({
  name: "CurrentComponent",
  components: { ChildComponent },
  emits: ["update:item"],
  props: {
    items: String,
  }
  methods: {
    onItemUpdated(item: string) {
      this.$emit("update:item", item);
    }
  }
});
</script>

<style></style>
```

Note that `item` is not stored locally as a data variable in `current-component` -- it is passed in as a prop from the parent component and any changes to it are immediately passed back up to the parent component using `$emit`.

How would one then reproduce this exact usage of `child-component` in JSX syntax **_only_**, inside a Composition API `setup` function, **_without_** changing the definition of `child-component` or the parent component in any way, and **_without_** storing `item` locally in `current-component` (i.e., not using `v-model`)?

The presence of the `:` in the event name (which must remain as per the rules above) is causing issues...

### 💻 Sample code

Invalid attempts:

```jsx
  return (
    <my-component
      item={item}
      // Obviously incorrect because "@" is not supported in JSX:
      @update:item={onItemUpdated}
    >
    </my-component>
  );
```

```jsx
  return (
    <my-component
      item={item}
      // Incorrect because this corresponds to an emit with name "updateItem", not "update:item":
      onUpdateItem={onItemUpdated}
    >
    </my-component>
  );
```

Also invalid are `onUpdate:Item`, `onUpdate-Item` and `onUpdate_item`.

**Comment by linkscope** [comment]
```
<my-component
      item={item}
      {...{'onUpdate:item':(value)=>xxx=value}}
>
```

**Comment by Amour1688** [comment]
try
https://vue-next-jsx-explorer.netlify.app/#%3Cchild-component%20v-model%3D%7B%5Bitem%2C%20'item'%5D%7D%20%2F%3E%0A
