### ISSUE TITLE
Got an error after replacing `@vue/babel-preset-jsx` with `@vue/babel-plugin-jsx`

### ISSUE THREAD

**Issue by yangjiang3973** [vuejs/jsx-next#355]
### 🧐 Problem Description
I have a vue2-similar framework and before it used @vue/babel-preset-jsx to translate JSX.

Recently I am refactoring it and make it more like vue3 APIs, so I also switched to use the new @vue/babel-plugin-jsx.

But I got this error:

`Module not found: Error: Can't resolve 'vue' in 'dev/demo/src'
 @ ./src/main.js 1:0-50 10:11-23`

I guess this new jsx plugin has a hard dependency on Vue3(@vue/babel-preset-jsx does not)? if I do not install Vue3 as a devDependency, I cannot use this repo..After I tried to install vue3, then no error reported.

But I hope all vue similar framework could use @vue/babel-plugin-jsx and it has no implicit dependency on vue3.

### 💻 Sample code
```js
import { createApp, h } from './runtime-dom/src/index';  // this is the runtime I wrote, not import from vue3

const app = createApp({
    data() {
        return {
            title: 'hello',
        };
    },
    render() {
        return <span>{this.title}</span>;
    },
});

app.mount('#app');
```

I haven't deeply looked into this repo's source code, but right now I guess the error is caused by importing the h function from vue3, but vue3 is not installed?

IMO, if the function h(i.e. createVNode) is provided, no need to import from vue3.

Otherwise, I do not know any reason to have a dependency on vue 

### 🚑 Other information
N/A

**Comment by yangjiang3973** [comment]
I checked the definition of render function after using `@vue/babel-plugin-jsx`.

Now it forces to use the createVNode function from vue3.

```js
render() {
    return Object(vue__WEBPACK_IMPORTED_MODULE_0__["createVNode"])("span", null, [this.title]);
}
```

I suggest if users import `h` function explicitly, @vue/babel-plugin-jsx should not hard-code vue3's `createVNode` into render function.

**Comment by Amour1688** [comment]
see https://github.com/vuejs/jsx-next/pull/322

**Comment by yangjiang3973** [comment]
@Amour1688 Thanks for your suggestion! I played with the pragma feature but still cannot solve the issue.

I tried in .babelrc like this:

```js
{
    "presets": ["@babel/env"],
    "plugins": [
        [
            "@vue/babel-plugin-jsx",
            {
                "pragma": "myOwnFunctionName",   // defaults to createVNode
            }
        ]
    ]
}
```

Then import my function like this:

```js
import { createApp, myOwnFunctionName } from 'src/path-of-their-file';
const app = createApp({
    data() {
        return {
            title: 'hello',
        };
    },
    render() {
        return <span>{this.title}</span>;
    },
});

app.mount('#app');
```
Is there any problem in my config here? Because I found it still uses the default createVNode function from vue3.

Can you give me an example? thanks again!

**Comment by Amour1688** [comment]
sorry, I will release a new version recently.
