### ISSUE TITLE
[BUG] The array or object is rendered incorrectly

### ISSUE THREAD

**Issue by ajuner** [vuejs/jsx-next#362]
### 🐛 Bug description

```js
import { ref } from 'vue';
...
setup() {
  const text = ref(["123"]);
  return () => (
    <div>{text.value}</div>
  )
}
```
Error: Maximum recursive updates exceeded. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function.

Render out 123

### 🏞 Desired result

1. No error
2. Render out `["123"]`

### 🚑 Other information
```js
import { reactive } from 'vue';
...
setup() {
  const text = reactive ({a:"123"});
  return () => (
    <div>{text}</div>
  )
}
```
Object will have no rendering results, And I want is `{ "a": "123" }`

**Comment by Amour1688** [comment]
You should use `JSON.stringfy`

**Comment by ajuner** [comment]
🤣
