### ISSUE TITLE
[Question] Help 内置<component />组件需要如何使用？

### ISSUE THREAD

**Issue by san-wi** [vuejs/jsx-next#378]
### 🧐 Problem Description
JSX无法解析内置 `<component \>` 组件，想知道是有可以调用组件的方法，还是目前不支持`<component \>`?

## .vue 文件编译结果

![image](https://user-images.githubusercontent.com/73974709/112972372-c6adff80-9182-11eb-9f20-af404ff08a33.png)

## .jsx 文件编译结果
![image](https://user-images.githubusercontent.com/73974709/112972465-df1e1a00-9182-11eb-9b20-0f863a5f066f.png)

### 💻 Sample code
```
// code
<KeepAlive>
 <component is="a" />
</KeepAlive>

// 结果
<component is="a"/>
```

**Comment by Amour1688** [comment]
直接 {a}

**Comment by sendya** [comment]
```JSX
// code
<KeepAlive>
  {a}
</KeepAlive>
```

**Comment by tangjinzhou** [comment]
`component` is a keyword in template, it should be a variable in jsx, you can define a `component` by yourself to achieve template behavior.

**Comment by tangjinzhou** [comment]
```html
<KeepAlive>
  {a}
</KeepAlive>
or
<KeepAlive>
  <A />
</KeepAlive>
or
<KeepAlive>
  {() => a}
</KeepAlive>
....
```
