### ISSUE TITLE
[Question] Help 如何在map循环成生成多个ref

### ISSUE THREAD

**Issue by TomatoDroid** [vuejs/jsx-next#381]
### 🧐 Problem Description
 {this.$props.modelValue.map(
    (item: TriggerConditionProps, index) => (
      <ItemWrapper>
        {/* @ts-ignore */}
        <ExpItem
          v-model={[item, ['modifier']]}
          ref="expItem"
        >
          <Button
            type="link"
            onClick={() => this.handleDeleteItem(index)}
          >
            删除
          </Button>
        </ExpItem>
      </ItemWrapper>
    )
  )}

如何获取数组形式的ref expItem, 而不是单个的ref

**Comment by linkscope** [comment]
你可以在外面做一个父节点ref，然后ref.value.children可以获取你遍历的所有节点

**Comment by Amour1688** [comment]
```tsx
import { defineComponent, reactive } from "vue";

export default defineComponent({
  setup() {
    const a = [1, 2, 3];
    const refs = reactive<Element[]>([]);
    
    return () =>
      a.map((k, i) => (
        <div
          key={i}
          ref={(ref) => refs[i] = ref as Element}
          class={`${k}`}
          onClick={() => {
            console.log(refs[i]);
          }}
        >
          {k}
        </div>
      ));
  },
});
```
