### ISSUE TITLE
怎么在webstrom中.vue后缀文件支持tsx语法

### ISSUE THREAD

**Issue by Niofh** [vuejs/jsx-next#384]
Vscode是支持的，但是遇到webstrom里面 .vue后缀文件不支持tsx语法

![image](https://user-images.githubusercontent.com/15324717/114126757-a3761380-992b-11eb-9937-65bebc75c082.png)

**Comment by linkscope** [comment]
。。。tsx是模板语法，不是一种语言，vue是另一种模板语法，把vue后缀改成tsx即可

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/114355295-dfb2a980-9ba1-11eb-983e-cd33b1209111.png)

如果不行，换 tsx 文件类型。 .vue 文件属于 vue 的模板文件

**Comment by Niofh** [comment]
那我全部把Vue文件后缀换成tsx

**Comment by Niofh** [comment]
> 。。。tsx是模板语法，不是一种语言，vue是另一种模板语法，把vue后缀改成tsx即可

但是vscode可以，就是webstrom检查报错了

**Comment by linkscope** [comment]
@Niofh vscode不会校验vue文件
