### ISSUE TITLE
[BUG] 自定义指令编译问题

### ISSUE THREAD

**Issue by heynext** [vuejs/jsx-next#404]
### 🐛 Bug description

根据 [withDirectives 文档](https://v3.cn.vuejs.org/api/global-api.html#withdirectives)，下图中红框部分应该是一个一维数组，代码见 https://vue-next-jsx-explorer.netlify.app/#%3Ca%20v-custom%3D%7B%5Bval%2C%20%22arg%22%2C%20%5B%22a%22%2C%20%22b%22%5D%5D%7D%20%2F%3E

![image](https://user-images.githubusercontent.com/13675762/116214692-876ed080-a779-11eb-9b8b-c675c2b0c646.png)

### 🏞 Desired result

期望编译后的结果是

```
import { withDirectives as _withDirectives, createVNode as _createVNode, resolveDirective as _resolveDirective } from "vue";

_withDirectives(_createVNode("a", null, null), [[_resolveDirective("custom"), val, "arg", ["a", "b"]]]);
```

### 🚑 Other information

此外自定义指令[单测用的语法](https://github.com/vuejs/jsx-next/blob/dev/packages/babel-plugin-jsx/test/index.test.tsx#L271)和[文档](https://github.com/vuejs/jsx-next#directives)中的也不太一样

**Comment by Amour1688** [comment]
这个 bug 应该是 #140 引入的，明天再看看，没问题发个版本
