### ISSUE TITLE
关于babel-loader以及ts-loader的问题

### ISSUE THREAD

**Issue by martSforever** [vuejs/jsx-next#408]
### 🧐 Problem Description

是这样的，不久前我写了个简易的babel-plugin，将jsx中的 v-model 编译为 modelValue 和 onUpdateModelValue；
这个plugin配合babel standalone在线编译代码也不错。然后我发现了一个问题：

- 在vue-cli创建的项目中，我发现是ts-loader先处理编译的，ts-loader直接就把jsx给编译了，也就是说v-model这个 jsx attribute没有了，变成了某个对象的属性。导致后续处理的babel-loader，我写的jsx插件没有生效；
- 我发现ts-loader还是有很多好用的地方，暂时不想放弃ts-loader。并不想换成 babel-loader + @babel/preset-typescript + ForkTsCheckerWebpackPlugin；

我的问题是：

- 在使用ts-loader先编译的前提下，vuecli中在处理tsx文件里面的jsx代码的时候是怎么处理的，如何在ts-loader之前先编译v-model这种指令；
- 我发现typescript的ast比babel的ast难用很多，目前在写typescript的转义插件感觉好麻烦，所以不想再维护一个typescript的插件；

希望大佬能给我一些建议或者指引，谢谢。

### 🚑 Other information

- 我目前是在React里面实现了一套CompositionAPI，想用上这个双向绑定的功能，所以才写的这个插件：[plain-design-composition](http://plain-pot.gitee.io/plain-design-doc/#composition%2Fcomposition-introduce.entire)
- 然后我希望使用vue-cli工程来创建React应用，毕竟有很多开箱即用的功能以及默认的许多优化，而且扩展webpack的配置也很方便，不太喜欢cra；所以就遇到了这个ts-loader的问题。

**Comment by Amour1688** [comment]
可以看下 TypeScript 关于 [JSX](https://www.typescriptlang.org/docs/handbook/jsx.html) 的文档，preserve 模式下，TS 就不会去处理 JSX 的语法了。

**Comment by martSforever** [comment]
多谢，我把问题解决了。jsx设置为preserve，target以及module设置为esnext，这样交给babel编译的代码就是对的了。非常感谢
