### ISSUE TITLE
[Could you build a unpkg version  officially] Help

### ISSUE THREAD

**Issue by Rainmen-xia** [vuejs/jsx-next#449]
### 🧐 Problem Description
I need run vue3 jsx in broswer ,need compiler jsx .can you build a unpkg version officailly.just like  https://unpkg.com/babel-plugin-transform-vue-jsx@3.7.0/dist/babel-plugin-transform-vue-jsx.min.js for vue2

**Comment by Rainmen-xia** [comment]
thanks a lot

**Comment by zouhangwithsweet** [comment]
`babel@7.x` doesnot support browser. `vue-jsx-next` is based on `babel@7.x`, I donot think it's can be worked in browser.

**Comment by zouhangwithsweet** [comment]
![image](https://user-images.githubusercontent.com/21095710/123266024-350a2000-d52e-11eb-9124-eaadb47d4f38.png)
Here is the babel docs. :)
