### ISSUE TITLE
[Question] v-models 的值怎么使用变量

### ISSUE THREAD

**Issue by hsiangleev** [vuejs/jsx-next#502]
请问v-models的值怎么使用变量，models的值由多个变量组合，例如
```ts
const name = ref('')
const age = ref(0)
const models = []
models.push([name.value, 'name'])
models.push([age.value, 'age', ['number']])
return () => (
    <Test v-models={models} />
)
```
我这样使用会报错`Internal server error: unknown: Property key of ObjectProperty expected node to be of a type ["Identifier","StringLiteral","NumericLiteral"] but instead got undefined`

**Comment by Amour1688** [comment]
`v-models` 暂时不支持变量。等 https://github.com/vuejs/jsx-next/pull/496 被合入，会逐渐废弃 `v-models` 的写法

**Comment by hsiangleev** [comment]
@Amour1688 那合并之后的新写法会支持使用变量吗
