### ISSUE TITLE
[Question] How to use v-memo in JSX / 如何在 JSX 里使用 v-memo 

### ISSUE THREAD

**Issue by YuYang019** [vuejs/jsx-next#527]
### 🧐 Problem Description

目前支持这个指令么？

**Comment by funny-family** [comment]
@YuYang019  I think you can try some use `withMemo` function.

```
<div v-memo="[item.id === selected, true]">
  ...
</div>
```

Vue template above compiles into this.
```
import { withMemo as _withMemo } from 'vue';

_withMemo([_ctx.item.id === _ctx.selected, true], () => (_openBlock(), _createElementBlock("div", null, [
  _createTextVNode(" ... ")
])), _cache, 0)
```

**Comment by tcastelly** [comment]
Hello,

Did you manage to use `withMemo` with jsx?
I tried in different way; inside a render function, in the setup ... not working as expected.

Thank you very much.
