### ISSUE TITLE
这个已经内置到cli 里面去了？

### ISSUE THREAD

**Issue by tyzma** [vuejs/jsx-next#73]
我用cli 新建了一个vue3.0的项目发现里面能够直接使用jsx

**Comment by xrkffgg** [comment]
应该是安装的时候有选项吧

**Comment by tyzma** [comment]
> 应该是安装的时候有选项吧

就只选了个babel，就能用了

**Comment by xrkffgg** [comment]
@Amour1688

**Comment by tyzma** [comment]
额  我把cli 里面用的几个babel 包放到vite 生成的项目里就能用jsx了 。。

**Comment by tyzma** [comment]
就像这样


![QQ图片20200829193842](https://user-images.githubusercontent.com/25071953/91635980-7c6b7100-ea2f-11ea-9a68-8eed16b0e7db.png)

**Comment by Amour1688** [comment]
From [this release](https://github.com/vuejs/vue-cli/releases/tag/v4.5.0), `@vue/babel-preset-app` has built-in this package.
