### ISSUE TITLE
mergeProps order error

### ISSUE THREAD

**Issue by tangjinzhou** [vuejs/jsx-next#94]
https://vue-next-jsx-explorer.netlify.app/#%3CButton%20loading%3D%7Btrue%7D%20%7B...otherProps%7D%3E%3C%2FButton%3E

```html
<Button loading={true} {...otherProps}></Button>
```
loading will override otherProps.loading

**Comment by Amour1688** [comment]
https://github.com/vuejs/jsx-next/commit/bf59811f4334dbc30fd62ba33a33926031dd8835
