### ISSUE TITLE
Does v-model support multiple bindings?

### ISSUE THREAD

**Issue by John60676** [vuejs/jsx-next#99]
I could not find the usage of `Multiple v-model bindings` in the documentation.

**Comment by John60676** [comment]
我的意思是如何绑定多个v-model
``` html
<CustomComponent v-model:foo="foo" v-model:bar="bar" />
```

**Comment by Amour1688** [comment]
https://vue-next-jsx-explorer.netlify.app/#%3CCustomComponent%20v-model%3D%7B%5Bfoo%2C%20'foo'%5D%7D%20v-model%3D%7B%5Bbar%2C%20'bar'%5D%7D%20%2F%3E%0A

**Comment by John60676** [comment]
但是我在 tsx 中使用会获得一个错误提示 ```JSX 元素不能具有多个名称相同的特性。ts(17001)```

**Comment by Amour1688** [comment]
```tsx
<CustomComponent
    foo={foo}
    bar={bar}
    {...{
      'onUpdate:foo': $event => foo = $event,
      'onUpdate:bar': $event => bar = $event,
    }}
  />
```

**Comment by Amour1688** [comment]
v-model   v-Model
